WIP: Monitoring
NickCraver/nickcraver.github.com pull request #36
Opened 2018-11-26 13:04 UTC by NickCraver

Initial pass at a monitoring blog post (and a few misc styling commits needed for it)

2018-11-27 10:18 UTC, m0sa requested changes
fixing typos

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +This is something that for example [StackExchage.Redis](https://github.com/StackExchange/StackExchange.Redis) uses to routinely check if the socket connection to Redis is active.
```suggestion
This is something that for example [StackExchange.Redis](https://github.com/StackExchange/StackExchange.Redis) uses to routinely check if the socket connection to Redis is active.
```

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +If we zoom out fom the data center, we need to see what's hitting us.
```suggestion
If we zoom out from the data center, we need to see what's hitting us.
```

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +Another case is just reporting an absolute point-in-time value, for example "This GPU is currenly 87°".
```suggestion
Another case is just reporting an absolute point-in-time value, for example "This GPU is currently 87°".
```

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +Years back, I threw together a client timings pipline when the pieces we needed first became available in browsers.
```suggestion
Years back, I threw together a client timings pipeline when the pieces we needed first became available in browsers.
```

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- All tabs are not requied--each is independent and only appears if configured.
```suggestion
- All tabs are not required--each is independent and only appears if configured.
```

2018-11-27 10:18 UTC, m0sa commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +We know of some things we'd like to do, such as impoving the alert editing experience and some other UI areas.
```suggestion
We know of some things we'd like to do, such as improving the alert editing experience and some other UI areas.
```

2018-11-27 20:11 UTC, NickCraver reviewed
Notes from Tom, thanks!

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +...and I was just kidding about email and [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation)...**all of those are GDPR concerns**. Keep retention and compliance in mind when log
```suggestion
...and I was just kidding about [GDPR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) only being a concern for email...**GDPR is a concern for all of the above**. Keep retention and compliance in mind when logging anything. It's another cost to consider.
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- SQL Count & Milliseconds
```suggestion
- SQL Count (queries) & Milliseconds
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- Redis Count & Milliseconds
```suggestion
- Redis Count (hits) & Milliseconds
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- HTTP Count & Milliseconds
```suggestion
- HTTP Count (requests sent) & Milliseconds
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- Tag Engine Count & Milliseconds
```suggestion
- Tag Engine Count (queries) & Milliseconds
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +- Elasticsearch Count & Milliseconds
```suggestion
- Elasticsearch Count (hits) & Milliseconds
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +That's [Fastly](https://www.fastly.com/).
```suggestion
That's usually our CDN & proxy: [Fastly](https://www.fastly.com/).
```

2018-11-27 20:11 UTC, NickCraver commented on blog/_posts/2018-11-29-stack-overflow-how-we-do-monitoring.markdown
> +Let's say our NY data center is primary at the moment, and CO is our backup (our default state).
```suggestion
Let's say our NY data center is primary at the moment, and CO is our backup.
```

2018-11-28 13:45 UTC, NickCraver commented
Go time! Merging in.

2018-11-28 13:46 UTC, merged